const flows = [
  {id:'014', title:'Launch analytics dashboard', role:'Receiving', status:'PROVISIONAL', desc:'Ship the production dashboard and complete the handover.', amount:'0.03', released:'0.01', step:2, total:3, current:'Frontend live', due:'Contest closes in 18h'},
  {id:'013', title:'Brand system refresh', role:'Receiving', status:'ACTIVE', desc:'A cohesive visual language for the next product chapter.', amount:'0.04', released:'0.02', step:3, total:4, current:'Handover complete', due:'Due in 2 days'},
  {id:'012', title:'Mobile onboarding flow', role:'Paying', status:'ACTIVE', desc:'A faster, clearer first-run experience for new users.', amount:'0.02', released:'0.00', step:1, total:2, current:'Prototype approved', due:'Due in 5 days'}
];
const grid = document.querySelector('#flow-grid'), list = document.querySelector('#flow-list');
function card(f){return `<article class="flow-card" data-id="${f.id}"><div class="flow-top"><span class="status ${f.status==='ACTIVE'?'active':'provisional'}">${f.status}</span><span class="eyebrow">#${f.id}</span></div><h3>${f.title}</h3><p>${f.desc}</p><div class="progress">${Array.from({length:f.total},(_,i)=>`<i class="${i<f.step-1?'done':i===f.step-1?'current':''}"></i>`).join('')}</div><div class="flow-meta"><span>Step ${f.step} of ${f.total}</span><b>${f.amount} GEN</b></div>${f.status==='PROVISIONAL'?`<div class="due">${f.due}</div>`:''}</article>`}
grid.innerHTML=flows.map(card).join(''); list.innerHTML=flows.map(card).join('');
function show(view){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active-view'));document.querySelector(`#${view}-view`).classList.add('active-view');document.querySelectorAll('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.view===view));document.querySelector('#page-title').textContent=view==='create'?'Create a flow':view[0].toUpperCase()+view.slice(1);window.scrollTo(0,0)}
document.addEventListener('click',e=>{const nav=e.target.closest('[data-view]');if(nav){e.preventDefault();show(nav.dataset.view)}const f=e.target.closest('.flow-card');if(f) detail(f.dataset.id);if(e.target.id==='connect'||e.target.id==='top-connect') toast('Wallet connection is ready for the deployed contract.');});
function detail(id){const f=flows.find(x=>x.id===id);show('detail');document.querySelector('#detail-content').innerHTML=`<div class="detail-hero"><div><p class="eyebrow">FLOW #${f.id} · ${f.role.toUpperCase()}</p><h1>${f.title}</h1><p class="lede">${f.desc}</p></div><span class="status ${f.status==='ACTIVE'?'active':'provisional'}">${f.status}</span></div><div class="detail-card"><div class="panel-head"><div><p class="eyebrow">SEQUENTIAL WORK</p><h2>Progress rail</h2></div><strong>${f.released} <small>GEN released</small></strong></div>${['Architecture delivered','Frontend live','Handover complete'].slice(0,f.total).map((s,i)=>`<div class="step-row"><span class="step-num ${i<f.step-1?'done':''}">${i<f.step-1?'✓':i+1}</span><div><h3>${s}</h3><p>${i<f.step-1?'Released and settled':i===f.step-1?(f.status==='PROVISIONAL'?'Review satisfied · contest window open':'Active · evidence ready to review'):'Locked until the previous step releases'}</p></div><div class="step-amount">0.01 <small>GEN</small></div></div>`).join('')}<div class="form-footer"><span>Escrowed ${f.amount} GEN · ${f.due}</span><button class="primary" onclick="toast('Transaction flow opened for the active step.')">${f.status==='PROVISIONAL'?'Finalize step':'Review active step'} <span>→</span></button></div></div>`}
document.querySelector('#flow-form').addEventListener('submit',e=>{e.preventDefault();toast('Flow draft saved. Connect a wallet to fund it on Studionet.');setTimeout(()=>show('overview'),900)});
function toast(msg){const t=document.querySelector('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>t.classList.remove('show'),3200)}
